
import React, { useState } from 'react';
import { generatePDF, downloadPDF, printPDF } from '../services/pdfService';

interface LegalNoticeProps {
  notices: {
    EN: string;
    HI: string;
    MR: string;
  };
}

const LegalNotice: React.FC<LegalNoticeProps> = ({ notices }) => {
  const [activeLang, setActiveLang] = useState<'EN' | 'HI' | 'MR'>('EN');
  const [copied, setCopied] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);

  const currentContent = notices[activeLang];
  const langLabels = {
    EN: 'English',
    HI: 'हिंदी (Hindi)',
    MR: 'मराठी (Marathi)'
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Legal Notice Draft - NyayaMitra</title>
            <style>
              body { 
                font-family: 'Georgia', serif; 
                padding: 40px; 
                line-height: 1.8; 
                color: #333;
                background-color: #f5f5f5;
              }
              .header {
                text-align: center;
                margin-bottom: 30px;
                border-bottom: 3px solid #1e293b;
                padding-bottom: 20px;
              }
              .header h1 { 
                margin: 0; 
                font-size: 28px; 
                font-weight: bold;
                letter-spacing: 2px;
              }
              .header p { 
                margin: 8px 0; 
                font-size: 13px; 
                color: #666; 
              }
              .notice { 
                white-space: pre-wrap; 
                border: 2px solid #e2e8f0; 
                padding: 35px; 
                background: linear-gradient(to bottom right, #f8fafc, #f1f5f9);
                font-family: Georgia, serif;
                font-size: 14px;
                line-height: 1.8;
              }
              .footer {
                margin-top: 30px;
                text-align: center;
                font-size: 11px;
                color: #999;
                border-top: 2px solid #ddd;
                padding-top: 20px;
              }
            </style>
          </head>
          <body>
            <div class="header">
              <h1>LEGAL NOTICE</h1>
              <p>Prepared by NyayaMitra - AI Legal Assistant for India</p>
              <p>Date: ${new Date().toLocaleDateString('en-IN')}</p>
            </div>
            <div class="notice">${currentContent}</div>
            <div class="footer">
              <p>⚠️ DISCLAIMER: This is an AI-generated legal document. Please review with a qualified legal professional before use.</p>
              <p>This document does not constitute legal advice or establish an attorney-client relationship.</p>
            </div>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  const handleDownload = () => {
    const element = document.createElement('a');
    const file = new Blob([currentContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `legal_notice_${activeLang}_${new Date().getTime()}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadPDF = () => {
    try {
      const pdf = generatePDF(currentContent, activeLang);
      downloadPDF(pdf, `legal_notice_${activeLang}_${new Date().getTime()}.pdf`);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF. Please try again.');
    }
  };

  return (
    <div className="bg-gradient-to-br from-slate-50 via-blue-50 to-slate-50 rounded-3xl border-2 border-slate-300 shadow-2xl overflow-hidden mt-8 animate-slide-in-from-bottom">
      {/* Premium Header */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 px-8 py-7 flex flex-col md:flex-row justify-between items-start md:items-center gap-5 border-b-4 border-amber-500">
        <div className="flex-1">
          <h3 className="text-white font-bold flex items-center gap-3 mb-2 uppercase tracking-widest text-lg">
            <span className="bg-gradient-to-br from-amber-400 to-orange-500 p-3 rounded-lg shadow-lg">
              <i className="fa-solid fa-file-contract text-slate-900 text-xl"></i>
            </span>
            Draft Legal Notice
          </h3>
          <p className="text-slate-400 text-sm">Professional legal document generated by NyayaMitra AI</p>
        </div>
        
        <div className="flex flex-wrap gap-3 w-full md:w-auto justify-start md:justify-end">
          {/* Language Selector */}
          <div className="flex bg-slate-700 rounded-xl p-1.5 border-2 border-slate-600 shadow-lg">
            {(['EN', 'HI', 'MR'] as const).map(lang => (
              <button
                key={lang}
                onClick={() => setActiveLang(lang)}
                className={`px-4 py-2 text-sm rounded-lg transition-all font-bold ${
                  activeLang === lang 
                    ? 'bg-gradient-to-r from-amber-400 to-orange-500 text-slate-900 shadow-lg scale-105' 
                    : 'text-slate-400 hover:text-white hover:bg-slate-600'
                }`}
                title={langLabels[lang]}
              >
                {lang}
              </button>
            ))}
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2 flex-wrap">
            <button 
              onClick={handleCopy}
              className={`text-sm px-4 py-2 rounded-lg transition-all flex items-center gap-2 font-bold border-2 transform hover:scale-105 ${
                copied
                  ? 'bg-green-500 text-white border-green-600 shadow-lg'
                  : 'bg-slate-700 hover:bg-slate-600 text-white border-slate-600 hover:border-slate-500 shadow-md hover:shadow-lg'
              }`}
              title="Copy to clipboard"
            >
              <i className={`fa-solid ${copied ? 'fa-check' : 'fa-copy'}`}></i>
              <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy'}</span>
            </button>
            <button 
              onClick={handleDownload}
              className="text-sm bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-all flex items-center gap-2 font-bold border-2 border-blue-500 hover:border-blue-400 shadow-md hover:shadow-lg transform hover:scale-105"
              title="Download as text file"
            >
              <i className="fa-solid fa-file-text"></i>
              <span className="hidden sm:inline">Download TXT</span>
            </button>
            <button 
              onClick={handleDownloadPDF}
              className="text-sm bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 text-white px-4 py-2 rounded-lg transition-all flex items-center gap-2 font-bold border-2 border-red-500 hover:border-red-400 shadow-md hover:shadow-lg transform hover:scale-105"
              title="Download as professional PDF"
            >
              <i className="fa-solid fa-file-pdf"></i>
              <span className="hidden sm:inline">PDF</span>
            </button>
            <button 
              onClick={handlePrint}
              className="text-sm bg-gradient-to-r from-indigo-600 to-indigo-700 hover:from-indigo-700 hover:to-indigo-800 text-white px-4 py-2 rounded-lg transition-all flex items-center gap-2 font-bold border-2 border-indigo-500 hover:border-indigo-400 shadow-md hover:shadow-lg transform hover:scale-105"
              title="Print or save as PDF"
            >
              <i className="fa-solid fa-print"></i>
              <span className="hidden sm:inline">Print</span>
            </button>
          </div>
        </div>
      </div>

      {/* Premium Info Banner */}
      <div className="bg-gradient-to-r from-amber-50 to-orange-50 border-b-2 border-amber-200 px-8 py-4 flex items-start gap-4 shadow-sm">
        <div className="text-amber-600 text-2xl flex-shrink-0 mt-0.5">
          <i className="fa-solid fa-lightbulb"></i>
        </div>
        <div className="flex-1">
          <p className="text-sm font-bold text-amber-900">Professional Legal Document</p>
          <p className="text-xs text-amber-800 mt-1 leading-relaxed">
            This draft notice is formatted according to Indian legal standards. Review with a qualified lawyer before sending to ensure compliance with applicable laws and court procedures in your jurisdiction.
          </p>
        </div>
      </div>

      {/* Content Area */}
      <div className="p-8 bg-white">
        <div className={`relative transition-all ${!isExpanded && 'max-h-[500px] overflow-hidden'}`}>
          <pre className={`whitespace-pre-wrap font-serif text-sm text-slate-800 leading-relaxed bg-gradient-to-br from-slate-50 via-white to-slate-50 p-8 border-2 border-slate-200 rounded-2xl shadow-md ${activeLang !== 'EN' ? 'hindi-text' : ''}`}>
            {currentContent}
          </pre>
          {!isExpanded && currentContent.length > 2000 && (
            <div className="absolute bottom-0 left-0 right-0 h-32 bg-gradient-to-t from-white via-white to-transparent flex items-end justify-center pb-4">
              <button
                onClick={() => setIsExpanded(true)}
                className="bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 text-white px-6 py-3 rounded-lg text-sm font-bold transition-all shadow-lg hover:shadow-xl transform hover:scale-105"
              >
                <i className="fa-solid fa-expand mr-2"></i>
                Expand to view full notice
              </button>
            </div>
          )}
        </div>
        
        {isExpanded && (
          <button
            onClick={() => setIsExpanded(false)}
            className="w-full mt-5 bg-gradient-to-r from-slate-200 to-slate-300 hover:from-slate-300 hover:to-slate-400 text-slate-700 px-4 py-3 rounded-lg text-sm font-bold transition-all transform hover:scale-102"
          >
            <i className="fa-solid fa-compress mr-2"></i>
            Collapse
          </button>
        )}
      </div>

      {/* Premium Footer with Disclaimers */}
      <div className="bg-gradient-to-r from-slate-100 via-blue-50 to-slate-100 border-t-2 border-slate-300 px-8 py-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-5">
          <div className="bg-white p-4 rounded-xl border-2 border-red-200 shadow-sm">
            <p className="text-xs font-bold text-red-700 uppercase tracking-wider mb-3 flex items-center gap-2">
              <i className="fa-solid fa-exclamation-triangle"></i>
              Important Disclaimers
            </p>
            <ul className="text-xs text-slate-700 space-y-1.5 font-medium">
              <li className="flex items-start gap-2">
                <span className="text-red-600 mt-0.5">•</span>
                <span>This is an AI-generated draft, not a final legal document</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-red-600 mt-0.5">•</span>
                <span>Consult a qualified lawyer before sending</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-red-600 mt-0.5">•</span>
                <span>No attorney-client relationship is established</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-red-600 mt-0.5">•</span>
                <span>Not a substitute for professional legal advice</span>
              </li>
            </ul>
          </div>
          <div className="bg-white p-4 rounded-xl border-2 border-green-200 shadow-sm">
            <p className="text-xs font-bold text-green-700 uppercase tracking-wider mb-3 flex items-center gap-2">
              <i className="fa-solid fa-check-circle"></i>
              Before Sending
            </p>
            <ul className="text-xs text-slate-700 space-y-1.5 font-medium">
              <li className="flex items-start gap-2">
                <span className="text-green-600 mt-0.5">✓</span>
                <span>Verify all factual details and dates</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-green-600 mt-0.5">✓</span>
                <span>Review with a legal professional</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-green-600 mt-0.5">✓</span>
                <span>Customize to your specific situation</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-green-600 mt-0.5">✓</span>
                <span>Check applicable limitation periods</span>
              </li>
            </ul>
          </div>
        </div>
        <p className="text-xs text-slate-600 italic bg-slate-50 px-4 py-3 rounded-lg border border-slate-200 text-center font-medium">
          Generated: {new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })} IST | Language: {langLabels[activeLang]}
        </p>
      </div>
    </div>
  );
};

export default LegalNotice;
